// Copyright (c) 2025, Futureverse Corporation Limited. All rights reserved.

namespace AssetRegister.Runtime.Interfaces
{
	/// <summary>
	/// Represents a response generated by the Client upon completing a GraphQL Request
	/// </summary>
	public interface IResponse
	{
		/// <summary>
		/// If the Request succeeded
		/// </summary>
		bool Success { get; }
		/// <summary>
		/// Any error generated by the client
		/// </summary>
		string Error { get; }
		/// <summary>
		/// Use to try to deserialize the response into a model object.
		/// </summary>
		/// <param name="result">The resulting model</param>
		/// <typeparam name="TResult">The type of model to retrieve</typeparam>
		/// <returns></returns>
		bool TryGetResult<TResult>(out TResult result) where TResult : class, IResult;
	}
}